#!/bin/sh
case "$1" in
  start)
    echo "Loading aesdchar module..."
    insmod /lib/modules/$(uname -r)/aesdchar.ko

    major=$(awk "\$2==\"aesdchar\" {print \$1}" /proc/devices)
    if [ -n "$major" ]; then
        echo "Creating /dev/aesdchar with major number $major"
        mknod /dev/aesdchar c $major 0
    else
        echo "Failed to find aesdchar major number"
    fi
    ;;
  stop)
    echo "Unloading aesdchar module..."
    rmmod aesdchar
    rm -f /dev/aesdchar
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0

